service: aws-lambda-image-processor

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: ${env:LAMBDA_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${env:OUTPUT_BUCKET}/*"
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:GetObjectAcl
      Resource: "arn:aws:s3:::${env:INPUT_BUCKET}/*"

functions:
  processor:
    handler: dist/index.handler
    environment:
      OUTPUT_BUCKET: ${env:OUTPUT_BUCKET}
    events:
      - s3:
          bucket: ${env:INPUT_BUCKET}
          event: s3:ObjectCreated:Put
          rules:
            - prefix: originals/
          existing: true

# If the OUTPUT BUCKET wasn't created, remove this commented code to create automatically
# resources:
#   Resources:
#     S3BucketOutputs:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: ${env:OUTPUT_BUCKET}
